using Shouldly;
using HagiCode.Libs.Core.Acp;
using HagiCode.Libs.Core.Execution;
using HagiCode.Libs.Providers;
using HagiCode.Libs.Providers.ClaudeCode;
using HagiCode.Libs.Providers.Codebuddy;
using HagiCode.Libs.Providers.Copilot;
using HagiCode.Libs.Providers.Codex;
using HagiCode.Libs.Providers.DeepAgents;
using HagiCode.Libs.Providers.Gemini;
using HagiCode.Libs.Providers.Hermes;
using HagiCode.Libs.Providers.Kimi;
using HagiCode.Libs.Providers.Kiro;
using HagiCode.Libs.Providers.OpenCode;
using HagiCode.Libs.Providers.Omp;
using HagiCode.Libs.Providers.Pi;
using HagiCode.Libs.Providers.QoderCli;
using HagiCode.Libs.Providers.Reasonix;
using Microsoft.Extensions.DependencyInjection;

namespace HagiCode.Libs.Providers.Tests;

public sealed class DependencyInjectionTests
{
    [Fact]
    public async Task AddHagiCodeLibs_registers_provider_registry_and_all_builtin_providers()
    {
        var services = new ServiceCollection();
        services.AddHagiCodeLibs();

        await using var serviceProvider = services.BuildServiceProvider();
        var registry = serviceProvider.GetRequiredService<ProviderRegistry>();
        var executionFacade = serviceProvider.GetRequiredService<ICliExecutionFacade>();
        var acpPool = serviceProvider.GetRequiredService<ICliAcpSessionPool>();
        var poolConfiguration = serviceProvider.GetRequiredService<HagiCode.Libs.Providers.Pooling.CliProviderPoolConfigurationRegistry>();
        var claudeProvider = serviceProvider.GetRequiredService<ICliProvider<ClaudeCodeOptions>>();
        var codebuddyProvider = serviceProvider.GetRequiredService<ICliProvider<CodebuddyOptions>>();
        var copilotProvider = serviceProvider.GetRequiredService<ICliProvider<CopilotOptions>>();
        var codexProvider = serviceProvider.GetRequiredService<ICodexProvider>();
        var deepAgentsProvider = serviceProvider.GetRequiredService<ICliProvider<DeepAgentsOptions>>();
        var geminiProvider = serviceProvider.GetRequiredService<ICliProvider<GeminiOptions>>();
        var hermesProvider = serviceProvider.GetRequiredService<ICliProvider<HermesOptions>>();
        var kimiProvider = serviceProvider.GetRequiredService<ICliProvider<KimiOptions>>();
        var kiroProvider = serviceProvider.GetRequiredService<ICliProvider<KiroOptions>>();
        var openCodeProvider = serviceProvider.GetRequiredService<ICliProvider<OpenCodeOptions>>();
        var piProvider = serviceProvider.GetRequiredService<ICliProvider<PiOptions>>();
        var ompProvider = serviceProvider.GetRequiredService<ICliProvider<OmpOptions>>();
        var qoderCliProvider = serviceProvider.GetRequiredService<ICliProvider<QoderCliOptions>>();
        var reasonixProvider = serviceProvider.GetRequiredService<ICliProvider<ReasonixOptions>>();
        var allProviders = serviceProvider.GetServices<ICliProvider>().ToArray();

        executionFacade.ShouldNotBeNull();
        acpPool.ShouldNotBeNull();
        poolConfiguration.HasSettings("claude-code").ShouldBeFalse();
        poolConfiguration.HasSettings("codebuddy").ShouldBeFalse();
        poolConfiguration.HasSettings("copilot").ShouldBeFalse();
        poolConfiguration.HasSettings("codex").ShouldBeFalse();
        poolConfiguration.HasSettings("deepagents").ShouldBeFalse();
        poolConfiguration.HasSettings("gemini").ShouldBeFalse();
        poolConfiguration.GetSettings("hermes").Enabled.ShouldBeTrue();
        poolConfiguration.GetSettings("hermes").IdleTimeout.ShouldBe(TimeSpan.FromHours(24));
        poolConfiguration.HasSettings("kimi").ShouldBeFalse();
        poolConfiguration.HasSettings("kiro-cli").ShouldBeFalse();
        poolConfiguration.HasSettings("qodercli").ShouldBeFalse();
        poolConfiguration.HasSettings("reasonix").ShouldBeFalse();
        poolConfiguration.HasSettings("omp").ShouldBeFalse();
        poolConfiguration.HasSettings("opencode").ShouldBeFalse();
        registry.GetProvider("claude-code").ShouldNotBeNull();
        registry.GetProvider("claude").ShouldNotBeNull();
        registry.GetProvider("claudecode").ShouldNotBeNull();
        registry.GetProvider("codebuddy").ShouldNotBeNull();
        registry.GetProvider("codebuddy-cli").ShouldNotBeNull();
        registry.GetProvider("copilot").ShouldNotBeNull();
        registry.GetProvider("github-copilot").ShouldNotBeNull();
        registry.GetProvider("githubcopilot").ShouldNotBeNull();
        registry.GetProvider("codex").ShouldNotBeNull();
        registry.GetProvider("codex-cli").ShouldNotBeNull();
        registry.GetProvider("openai-codex").ShouldNotBeNull();
        registry.GetProvider("deepagents").ShouldNotBeNull();
        registry.GetProvider("deepagents-acp").ShouldBeNull();
        registry.GetProvider("gemini").ShouldNotBeNull();
        registry.GetProvider("gemini-cli").ShouldNotBeNull();
        registry.GetProvider("hermes").ShouldNotBeNull();
        registry.GetProvider("hermes-cli").ShouldNotBeNull();
        registry.GetProvider("kimi").ShouldNotBeNull();
        registry.GetProvider("kimi-cli").ShouldNotBeNull();
        registry.GetProvider("kiro-cli").ShouldNotBeNull();
        registry.GetProvider("opencode").ShouldNotBeNull();
        registry.GetProvider("open-code").ShouldNotBeNull();
        registry.GetProvider("opencode-cli").ShouldNotBeNull();
        registry.GetProvider("pi").ShouldNotBeNull();
        registry.GetProvider("pi-cli").ShouldNotBeNull();
        registry.GetProvider("omp").ShouldNotBeNull();
        registry.GetProvider("omp-cli").ShouldNotBeNull();
        registry.GetProvider("qodercli").ShouldNotBeNull();
        registry.GetProvider("reasonix").ShouldNotBeNull();
        claudeProvider.ShouldBeOfType<ClaudeCodeProvider>();
        codebuddyProvider.ShouldBeOfType<CodebuddyProvider>();
        copilotProvider.ShouldBeOfType<CopilotProvider>();
        codexProvider.ShouldBeOfType<CodexProvider>();
        deepAgentsProvider.ShouldBeOfType<DeepAgentsProvider>();
        geminiProvider.ShouldBeOfType<GeminiProvider>();
        hermesProvider.ShouldBeOfType<HermesProvider>();
        kimiProvider.ShouldBeOfType<KimiProvider>();
        kiroProvider.ShouldBeOfType<KiroProvider>();
        openCodeProvider.ShouldBeOfType<OpenCodeProvider>();
        piProvider.ShouldBeOfType<PiProvider>();
        ompProvider.ShouldBeOfType<OmpProvider>();
        qoderCliProvider.ShouldBeOfType<QoderCliProvider>();
        reasonixProvider.ShouldBeOfType<ReasonixProvider>();
        allProviders.ShouldContain(provider => provider is CodexProvider);
        allProviders.ShouldContain(provider => provider is GeminiProvider);
        allProviders.ShouldContain(provider => provider is HermesProvider);
        allProviders.ShouldContain(provider => provider is KimiProvider);
        allProviders.ShouldContain(provider => provider is KiroProvider);
        allProviders.ShouldContain(provider => provider is OpenCodeProvider);
        allProviders.ShouldContain(provider => provider is PiProvider);
        allProviders.ShouldContain(provider => provider is OmpProvider);
        allProviders.ShouldContain(provider => provider is DeepAgentsProvider);
        allProviders.ShouldContain(provider => provider is ReasonixProvider);
        registry.GetProvider<CopilotOptions>("copilot").ShouldBeOfType<CopilotProvider>();
        registry.GetProvider<CopilotOptions>("github-copilot").ShouldBeOfType<CopilotProvider>();
        registry.GetProvider<CopilotOptions>("githubcopilot").ShouldBeOfType<CopilotProvider>();
        registry.GetProvider<ClaudeCodeOptions>("claude").ShouldBeOfType<ClaudeCodeProvider>();
        registry.GetProvider<ClaudeCodeOptions>("claudecode").ShouldBeOfType<ClaudeCodeProvider>();
        registry.GetProvider<CodebuddyOptions>("codebuddy-cli").ShouldBeOfType<CodebuddyProvider>();
        registry.GetProvider<DeepAgentsOptions>("deepagents").ShouldBeOfType<DeepAgentsProvider>();
        registry.GetProvider<DeepAgentsOptions>("deepagents-acp").ShouldBeNull();
        registry.GetProvider<GeminiOptions>("gemini").ShouldBeOfType<GeminiProvider>();
        registry.GetProvider<GeminiOptions>("gemini-cli").ShouldBeOfType<GeminiProvider>();
        registry.GetProvider<HermesOptions>("hermes").ShouldBeOfType<HermesProvider>();
        registry.GetProvider<HermesOptions>("hermes-cli").ShouldBeOfType<HermesProvider>();
        registry.GetProvider<KimiOptions>("kimi").ShouldBeOfType<KimiProvider>();
        registry.GetProvider<KimiOptions>("kimi-cli").ShouldBeOfType<KimiProvider>();
        registry.GetProvider<KiroOptions>("kiro-cli").ShouldBeOfType<KiroProvider>();
        registry.GetProvider<OpenCodeOptions>("opencode").ShouldBeOfType<OpenCodeProvider>();
        registry.GetProvider<OpenCodeOptions>("open-code").ShouldBeOfType<OpenCodeProvider>();
        registry.GetProvider<OpenCodeOptions>("opencode-cli").ShouldBeOfType<OpenCodeProvider>();
        registry.GetProvider<PiOptions>("pi").ShouldBeOfType<PiProvider>();
        registry.GetProvider<PiOptions>("pi-cli").ShouldBeOfType<PiProvider>();
        registry.GetProvider<OmpOptions>("omp").ShouldBeOfType<OmpProvider>();
        registry.GetProvider<OmpOptions>("omp-cli").ShouldBeOfType<OmpProvider>();
        registry.GetProvider<QoderCliOptions>("qodercli").ShouldBeOfType<QoderCliProvider>();
        registry.GetProvider<ReasonixOptions>("reasonix").ShouldBeOfType<ReasonixProvider>();
        registry.GetAllProviders().Select(static provider => provider.Name).ShouldBe(["claude-code", "codebuddy", "copilot", "codex", "deepagents", "gemini", "hermes", "kimi", "kiro-cli", "opencode", "pi", "omp", "qodercli", "reasonix"], ignoreOrder: true);
    }
}
